kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:

# - name: tests
#   image: golang:1.14
#   commands:
#   - go get -u github.com/rakyll/gotest
#   - gotest -v ./...

- name: tag
  image: bitnami/git
  commands:
  - git fetch --tags --verbose
  - TAG=$(git describe --tags --always --dirty)
  - printf $${TAG} > .tags
    # - printf "$(git describe --tags --always --dirty)" > .tags
  - cat .tags

# - name: tag-latest
#   image: bitnami/git
#   commands:
#   - printf ",latest" >> .tags
#   - cat .tags
#   when:
#     branch:
#     - master

# - name: publish
#   image: plugins/docker
#   settings:
#     dockerfile: Dockerfile
#     password:
#       from_secret: dockerhub-pass
#     repo: "${CI_REPO}"
#     username: digtux
#   when:
#     branch:
#     - master
#     - develop
#     - feature/*

trigger:
  branch:
  - develop
  - master
  - feature/*
  event:
  - push
  - tag

