---
colorschemes:

## example colorschemes..
## EG:
## - if your hostname is my-prod-k8s.example.com
## - then the colour will be set to "red"

## find a color that suites you here: https://vuetifyjs.com/en/styles/colors/#material-colors

- verbs:
  - prod
  - live
  color: "red darken-3"

- verbs:
  - staging
  color: "indigo darken-1"

- verbs:
  - dev
  color: "teal lighten-4"
